version: '3.7'

services:
  echo-lambda:
    image: echo-lambda
    build:
      args:
        BINARY_NAME: echo
      context: .
    container_name: echo-lambda
    ports:
      - "9001:8080"
  hello-lambda:
    image: hello-lambda
    build:
      context: .
    container_name: hello-lambda
    ports:
      - "9000:8080"
