# https://gallery.ecr.aws/lambda/go
FROM public.ecr.aws/lambda/go:1

ARG BINARY_NAME="hello"
ARG REGION="us-east-1"
ARG FUNCTION_NAME="HelloFunction"

COPY "tmp/${BINARY_NAME}.zip" /tmp/

RUN unzip "/tmp/${BINARY_NAME}.zip" -d ${LAMBDA_TASK_ROOT}/
RUN mv ${LAMBDA_TASK_ROOT}/${BINARY_NAME} ${LAMBDA_TASK_ROOT}/bootstrap

ENV AWS_LAMBDA_FUNCTION_MEMORY_SIZE=128
ENV AWS_LAMBDA_FUNCTION_TIMEOUT=5
ENV AWS_LAMBDA_FUNCTION_HANDLER=bootstrap
ENV AWS_LAMBDA_FUNCTION_NAME=${FUNCTION_NAME}
ENV AWS_LAMBDA_FUNCTION_VERSION="\$LATEST"
ENV AWS_LAMBDA_LOG_GROUP_NAME="aws/lambda/${FUNCTION_NAME}"
ENV AWS_LAMBDA_LOG_STREAM_NAME="\$LATEST"

ENV AWS_REGION="${REGION}"
ENV AWS_DEFAULT_REGION="${REGION}"
ENV AWS_ACCESS_KEY_ID="defaultkey"
ENV AWS_SECRET_ACCESS_KEY="defaultsecret"
ENV AWS_ACCOUNT_ID="123456789012"

CMD [ "./bootstrap" ]
