version: 3

includes:
  tf: ./TFTasks.yml
  sam:
    taskfile: ./SAMTasks.yml
    internal: true

tasks:
  default: task --list
  clean: ./bin/clean
  build:
    desc: Builds all Go packages under the "functions" directory
    cmds:
      - ./bin/build
    sources:
      - functions/**/*.go
    generates:
      - out/**/*
  package:
    desc: Creates a zip archive for each Lambda binary
    deps:
      - build
    cmds:
      - ./bin/package
    sources:
      - out/**/*
    generates:
      - tmp/**

  sam-local:
    desc: Start a Lambda container with AWS SAM
    deps:
      - package
    cmds:
      - task: sam:lambda

  invoke-local:
    desc: Sends a Lambda request to the running local Lambda docker container
    cmds:
      - curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d @events/apigw-request.json

  integration-test:
    desc: Run integration test with docker-compose
    deps:
      - package
    cmds:
       - docker compose -f docker-compose.integration.yml up --exit-code-from integration --build --force-recreate
       - docker compose -f docker-compose.integration.yml down
