version: 3

tasks:
  default: task --list
  clean: ./bin/clean
  build:
    desc: Builds all Go packages under the "functions" directory
    cmds:
      - ./bin/build
    sources:
      - functions/**/*.go
    generates:
      - out/**/*
  package:
    desc: Creates a zip archive for each Lambda binary
    deps:
      - build
    cmds:
      - ./bin/package
    sources:
      - out/**/*
    generates:
      - tmp/**

  dc-up:
    desc: Runs the docker-compose to use for local Lambda testing
    deps:
      - package
    cmds:
      - docker-compose -f docker-compose.local.yml up -d
  dc-down:
    desc: Stops the docker-compose containers used for local Lambda testing
    cmds:
      - docker-compose -f docker-compose.local.yml down

  tf-docs:
    desc: Generate Terraform Docs
    cmds:
      - docker run --rm -v "$(pwd)/terraform:/terraform-docs" -u $(id -u) quay.io/terraform-docs/terraform-docs:0.16.0 markdown --output-file README.md --output-mode inject --recursive --recursive-path ../../../modules /terraform-docs/dev/us-east-1/my-serverless-app

  tf-init:
    desc: Init the Terraform
    dir: terraform/dev/us-east-2/my-serverless-app
    cmds:
      - terraform init

  tf-plan:
    desc: Run a Terraform plan
    dir: terraform/dev/us-east-2/my-serverless-app
    cmds:
      - terraform plan -out=tf.out

  tf-show:
    desc: Read the Terraform plan file
    dir: terraform/dev/us-east-2/my-serverless-app
    cmds:
      - terraform show tf.out

  invoke-local:
    desc: Sends a Lambda request to the running local Lambda docker container
    cmds:
      - curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d @events/apigw-request.json

  integration-test:
    desc: Run integration test with docker-compose
    cmds:
       - docker compose -f docker-compose.integration.yml up --exit-code-from integration
       - docker compose -f docker-compose.integration.yml down
