openapi: 3.0.3
info:
  title: My Serverless App
  description: Serverless Application using AWS Serverless architecture, deployed using Terraform
  version: 1.0.0
  contact:
    name: Adam Kijowski
    email: akijowski@twilio.com
externalDocs:
  description: Project repo
  url: 'https://github.com/akijowski/aws-tf-serverless-demo'
tags:
  - name: lambda
    description: lambda operations
  - name: mocks
    description: mock operations
paths:
  /hello:
    get:
      tags:
        - lambda
      operationId: get-hello-world
      summary: Hello World Lambda
      parameters:
        - name: name
          in: query
          required: false
          description: change the name in the response with this cool query param
          schema:
            type: string
      description: Invokes a simple Hello World Lambda
      responses:
        '200':
          $ref: '#/components/responses/HelloWorldResponse'
      x-amazon-apigateway-request-validator: params-only
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri: ${helloLambdaInvocationArn}

  /keys:
    post:
      tags:
        - lambda
      operationId: post-keys
      summary: Create a k-v entry
      description: Writes a new key/value entry
      requestBody:
        $ref: "#/components/requestBodies/KVCreationRequest"
      responses:
        '201':
          $ref: "#/components/responses/KVCreationResponse"
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_templates
        uri: ${keyLambdaInvocationArn}

  /ping:
    get:
      tags:
        - mocks
      operationId: get-ping
      summary: Ping Pong
      description: When you ping, it pongs
      responses:
        '200':
          $ref: '#/components/responses/PongResponse'
      x-amazon-apigateway-request-validator: none
      x-amazon-apigateway-integration:
        type: mock
        passthroughBehavior: when_no_templates
        requestTemplates:
          # https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-mock-integration.html
          'text/plain': '{"statusCode": 200}'
          # This is only needed if you want to call the method through the console.  It only sends application/json
          'application/json': '{"statusCode": 200}'
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              text/plain:
                "pong"


x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
  none:
    validateRequestBody: false
    validateRequestParameters: false

components:
  requestBodies:
    KVCreationRequest:
      description: Key-value entry creation request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/KVEntry"

  responses:
    KVCreationResponse:
      description: Successful key-value entry creation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/KVEntry"

    PongResponse:
      description: A simple ping-pong response
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/Pong'

    HelloWorldResponse:
      description: Hello-world response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HelloWorld'

  schemas:
    KVEntry:
      description: An entry in the Key-Value store
      type: object
      properties:
        key:
          type: string
          minLength: 3
        value:
          type: string
          minLength: 3
      required:
        - key
        - value

    Pong:
      description: A simple ping-pong response body
      type: string
      example: 'pong'
    HelloWorld:
      description: A hello-world Lambda response
      type: object
      properties:
        message:
          type: string
          minLength: 1
      required:
        - message
      example:
        message: Hello World
